In [1]:
import pandas as pd 
df = pd.read_csv("dataset_study.csv")
df.head()

   student_id  study_hours  grade
0           1         9.15  91.91
1           2         9.37  86.81
2           3         2.86  53.39
3           4         8.30  85.52
4           5         6.42  77.98

In [5]:
df.drop('student_id' , axis=1 , inplace = True)

In [6]:
df.head()

   study_hours  grade
0         9.15  91.91
1         9.37  86.81
2         2.86  53.39
3         8.30  85.52
4         6.42  77.98

In [7]:
df.describe()

       study_hours        grade
count  5000.000000  5000.000000
mean      5.031654    64.969712
std       2.910579    17.657329
min       0.000000    15.520000
25%       2.520000    51.717500
50%       5.050000    64.975000
75%       7.582500    78.710000
max      10.000000   100.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  5000 non-null   float64
 1   grade        5000 non-null   float64
dtypes: float64(2)
memory usage: 78.3 KB